package psp.exercicio9;

import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    // Variables de uso público
    Subir sub;
    Bajar baj;

    Control control = new Control();

    public Main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Subir = new javax.swing.JButton();
        btn_Bajar = new javax.swing.JButton();
        txt_Caja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Subir.setText("Subir");
        btn_Subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubirActionPerformed(evt);
            }
        });

        btn_Bajar.setText("Bajar");
        btn_Bajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BajarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_Subir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btn_Bajar)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(txt_Caja, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(txt_Caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Subir)
                    .addComponent(btn_Bajar))
                .addGap(85, 85, 85))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubirActionPerformed

        // Cada vez que pulsamos el boton, crea un nuevo objeto para no tener que crear nuevos objetoas para crear nuevo hilos
        new Subir(control, condicion(txt_Caja.getText())).start();
        // Borramos el contenido de la caja de texto
        txt_Caja.setText("");
    }//GEN-LAST:event_btn_SubirActionPerformed

    private void btn_BajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BajarActionPerformed

        // Cada vez que pulsamos el boton, crea un nuevo objeto para no tener que crear nuevos objetoas para crear nuevo hilos
        new Bajar(control, condicion(txt_Caja.getText())).start();
        // Borramos el contenido de la caja de texto
        txt_Caja.setText("");

    }//GEN-LAST:event_btn_BajarActionPerformed
    public String condicion(String piso) {
        boolean condicion = false;
        while (condicion == false) {
            if (Integer.parseInt(piso) >= 1 && Integer.parseInt(piso) <= 20) {
                condicion = true;
                return piso;
            } else {
                piso = JOptionPane.showInputDialog("Piso no existe");
            }
        }

        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bajar;
    private javax.swing.JButton btn_Subir;
    private javax.swing.JTextField txt_Caja;
    // End of variables declaration//GEN-END:variables
}
